name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  debang:
    path: ../

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
